version: '3.9'

services:

  app:
    build: .
    container_name: springboot-login-registration
    ports:
      - "5000:5000"  # Expone el puerto de la aplicación
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/${SPRING_DATASOURCE_DB}
  db:
    image: postgres:latest
    container_name: postgres_login_registration_db
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"

    volumes:
       - ./postgres:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script para que se ejecute al iniciar